In [1]:
import numpy as np
import pandas as pd
from schema import HIGH_PERFORMER_COL, INDEX_COL, PREDICTOR_COLS, \
    PROTECTED_GROUP_COL, RETAINED_COL, TARGET_COLS
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier


In [2]:
predictor_cols = list(PREDICTOR_COLS)
target_cols = list(TARGET_COLS)
usecols = [INDEX_COL] + target_cols + predictor_cols
train = pd.read_csv(
    "../data/train.csv",
    index_col="UNIQUE_ID",
    usecols=usecols,
    na_values=" "
)
train.dropna(subset=target_cols, inplace=True)

X = train[predictor_cols]
y = train[target_cols]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)


In [3]:
estimator = XGBClassifier(n_estimators=1000, learning_rate=0.05, n_jobs=4)
model = OneVsRestClassifier(estimator)

pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('model', model),
])
pipeline.fit(X_train, y_train)
y_proba = pipeline.predict_proba(X_test)


In [4]:
y_pred = y_proba > 0.5
print(accuracy_score(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(accuracy_score(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(accuracy_score(y_test[RETAINED_COL], y_pred[:, 2]))
# print(accuracy_score(y_test[RETAINED_COL], y_pred[:, 2]))


0.6362484157160964
0.6869455006337135
0.5652724968314322


In [5]:
train.shape

(7890, 123)

In [6]:
y_pred = y_proba > 0.5
print(accuracy_score(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(confusion_matrix(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(accuracy_score(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(confusion_matrix(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(accuracy_score(y_test[RETAINED_COL], y_pred[:, 2]))
print(confusion_matrix(y_test[RETAINED_COL], y_pred[:, 2]))


0.6362484157160964


NameError: name 'confusion_matrix' is not defined

In [7]:
import numpy as np
import pandas as pd
from schema import HIGH_PERFORMER_COL, INDEX_COL, PREDICTOR_COLS, \
    PROTECTED_GROUP_COL, RETAINED_COL, TARGET_COLS
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier


In [8]:
y_pred = y_proba > 0.5
print(accuracy_score(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(confusion_matrix(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(accuracy_score(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(confusion_matrix(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(accuracy_score(y_test[RETAINED_COL], y_pred[:, 2]))
print(confusion_matrix(y_test[RETAINED_COL], y_pred[:, 2]))


0.6362484157160964
[[389 104]
 [183 113]]
0.6869455006337135
[[418  88]
 [159 124]]
0.5652724968314322
[[125 216]
 [127 321]]


In [9]:
y_pred = y_proba > 0.5
print(HIGH_PERFORMER_COL)
print(accuracy_score(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(confusion_matrix(y_test[HIGH_PERFORMER_COL], y_pred[:, 0]))
print(accuracy_score(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(confusion_matrix(y_test[PROTECTED_GROUP_COL], y_pred[:, 1]))
print(accuracy_score(y_test[RETAINED_COL], y_pred[:, 2]))
print(confusion_matrix(y_test[RETAINED_COL], y_pred[:, 2]))


High_Performer
0.6362484157160964
[[389 104]
 [183 113]]
0.6869455006337135
[[418  88]
 [159 124]]
0.5652724968314322
[[125 216]
 [127 321]]
